spring.application.name=uxilibris-backend
server.port=8080
server.address=0.0.0.0

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/UxiLibrisDB?createDatabaseIfNotExists=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=abc123.

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true